[project]
name = "fabrique"
version = "0.4.0"
description = "Foundation for modern ML research"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-tunix[prod]>=0.1.6",
    "optax>=0.2.5",
    "multimethod>=2.0",
]

[dependency-groups]
dev = [
    "accelerate>=1.13.0",
    "black>=25.1.0",
    "ipython>=9.2.0",
    "isort>=6.0.1",
    "mypy>=1.15.0",
    "pytest>=8.4.1",
    "ruff>=0.13.1",
    "torch>=2.11.0",
    "transformers>=4.52",
]
extra = [
    "pillow>=11.2.1",
    "datasets>=4.1.1",
]


[tool.uv]
default-groups = ["dev", "extra"]

[tool.uv.sources]
google-tunix = { git = "https://github.com/google/tunix", branch = "main" }
